# Generated by Django 4.2.6 on 2023-10-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.login'),
            preserve_default=False,
        ),
    ]
