# Generated by Django 4.2.6 on 2023-10-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_users_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManageBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_email', models.CharField(max_length=100)),
                ('bank_phone', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.login')),
            ],
        ),
    ]
