# Generated by Django 4.2.6 on 2023-10-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_recipient_donor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminManageBank',
            new_name='bank_reg',
        ),
    ]
