# Generated by Django 4.2.6 on 2023-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_recipient_booking_bank_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, unique=True)),
                ('recipient_blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, unique=True)),
                ('compatible', models.BooleanField()),
            ],
        ),
    ]
