# Generated by Django 4.2.6 on 2023-11-18 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_bloodcompatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_litres', models.CharField(max_length=20)),
                ('b_date', models.DateField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.donor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.users')),
            ],
        ),
        migrations.DeleteModel(
            name='BloodCompatibility',
        ),
    ]
