# Generated by Django 4.2.6 on 2023-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_blood_booking_delete_bloodcompatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_booking',
            name='b_status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
