# Generated by Django 4.2.6 on 2023-11-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_blood_booking_b_status_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
