# Generated by Django 4.2.6 on 2023-11-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
