# Generated by Django 4.2.6 on 2023-11-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_donor_last_donation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
