# Generated by Django 4.2.6 on 2023-11-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
