# Generated by Django 4.2.6 on 2023-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_delete_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_group',
            name='b_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
