# Generated by Django 4.2.6 on 2024-02-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_blood_group_b_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('allow_self_donation', models.BooleanField(default=True)),
            ],
        ),
    ]
