# Generated by Django 4.2.6 on 2024-03-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_selfdonationform_delete_donationcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
