# Generated by Django 4.2.6 on 2024-03-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_donationdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=50)),
                ('blood_type', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DonorRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.donationdrive')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.users')),
            ],
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ManyToManyField(to='bank.bloodproduct')),
            ],
        ),
    ]
